
default_platform(:android)

platform :android do
  desc "Ditribute the app to Firebase App Distribution"
  lane  :distribute_to_firebase do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      apk_path: "../#{ENV["BUILD_ARTIFACT"]}",
      android_artifact_path: "app/build/outputs/apk/release/app-release.apk",
      android_artifact_type: "APK",
      groups: "testers",
      release_notes: "release_notes_from_git_commits",
      debug: true
    )
  end
end
